version: '3'

services:
  # Blockchain node (using Ganache for Ethereum development)
  blockchain:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: --deterministic --mnemonic "decentralized storage system" --host 0.0.0.0

  # Coordinator service - manages storage nodes and file metadata
  coordinator:
    build: ./coordinator
    ports:
      - "5001:5001"
    environment:
      - BLOCKCHAIN_URL=http://blockchain:8545
    volumes:
      - coordinator_data:/app/data
    depends_on:
      - blockchain

  # Client API
  client-api:
    build: ./client
    environment:
      - COORDINATOR_URL=http://coordinator:5001
      - BLOCKCHAIN_URL=http://blockchain:8545
    ports:
      - "5002:5002"
    volumes:
      - ./client:/app
    depends_on:
      - coordinator
      - blockchain

  # Web interface
  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - CLIENT_API_URL=http://client-api:5002
    volumes:
      - ./web:/app
    depends_on:
      - client-api

volumes:
  coordinator_data: