version: '3'

services:

  storage1:
    build: ./storage_node
    environment:
      - NODE_ID=ashu
      - STORAGE_LIMIT_MB=1000
      - COORDINATOR_URL=http://172.31.112.248:5001
      - HOST_IP=172.31.112.248
      - PORT=6001
      - WALLET_ADDRESS=0xfde653c3537040abacabee18a38d3b950a1d6ab3
    ports:
      - "6001:6000"
    volumes:
      - storage1_data:/app/storage

volumes:
  storage1_data: