version: '3'

services:

  storage1:
    build: ./storage_node
    environment:
      - NODE_ID=node3
      - STORAGE_LIMIT_MB=1000
      - COORDINATOR_URL=http://172.31.112.248:5001
      - HOST_IP=172.31.112.248
      - PORT=6001
      - WALLET_ADDRESS=0x22e8a7bcf589b82dcc15347f6a3f12a276310da2
    ports:
      - "6001:6000"
    volumes:
      - storage1_data:/app/storage

volumes:
  storage1_data: